### ISSUE TITLE
Multiple ways to build the same target

### ISSUE THREAD

**Issue by newbies155** [nanobyte-dev/nanobyte_os#13]
When i follow the steps in the description, i try to run "scons toolchain", but i get this instead..

scons: Reading SConscript files ...

scons: *** Multiple ways to build the same target were specified for: arch/i686/gdt.o  (from ['/mnt/c/Users/[...]/Documents/OS/src/kernel/arch/i686/gdt.c'] and from ['/mnt/c/Users/[...]/Documents/OS/src/kernel/arch/i686/gdt.asm'])
File "/mnt/c/Users/[...]/Documents/OS/src/kernel/SConscript", line 25, in <module>

**Comment by chibicitiberiu** [comment]
The error appears when there are 2 files with the same name in the same folder, but different extensions. For example, `gdt.asm` and `gdt.c` (both will result in `gdt.o`, and the build system doesn't know how to deal with that).

I fixed this issue, maybe in a newer commit than the one you have.

**Comment by newbies155** [comment]
In the latest commit there is actually a "(file)_asm.asm" for every file, so i just deleted the "(file).asm" and left the "(file)_asm.asm", it worked.
