### ISSUE TITLE
Scons error toolchain

### ISSUE THREAD

**Issue by franticboDev** [nanobyte-dev/nanobyte_os#16]
I tried to do `scons toolchain` but it's giving me this error: 
_**./scripts/setup_toolchain.sh: line 34: pushd: ../.toolchains: No such file or directory**_
Help me!

**Comment by WoffleTbh** [comment]
You need to create the `.toolchains` directory, or change where you want to build the toolchain

**Comment by franticboDev** [comment]
The error still apears after that
![image](https://user-images.githubusercontent.com/95584375/192221901-8b074e68-4155-4d7a-9e7b-2bccd44edd37.png)

**Comment by chibicitiberiu** [comment]
In the config file, .toolchains is set in the parent directory (the directory above where the project is stored). Modify it to ".toolchains" to fix it, and then run `scons toolchain` to build the toolchain.

**Comment by franticboDev** [comment]
Thx

**Comment by franticboDev** [comment]
Now again it's giving me an error for --prefix:
![image](https://user-images.githubusercontent.com/95584375/192245402-ebccbb20-e2d8-4c30-8a8b-62b6a413e8c9.png)

**Comment by chibicitiberiu** [comment]
The easiest fix is to modify setup_toolchain.sh line 23, replace `TOOLCHAINS_DIR="$1"` with `TOOLCHAINS_DIR=$(realpath "$1")`

**Comment by franticboDev** [comment]
@chibicitiberiu and @WoffleTbh thanks a lot!
