### ISSUE TITLE
Scons error on WSL2/normal linux too.

### ISSUE THREAD

**Issue by ajh123** [nanobyte-dev/nanobyte_os#17]
I tried to run ```scons toolchain``` on a WSL2 Ubuntu environment. I have installed all the dependencies.
But I get this
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
./scripts/setup_toolchain.sh ../.toolchains
sh: 1: ./scripts/setup_toolchain.sh: not found
scons: *** [toolchain] Error 127
scons: building terminated because of errors.
```
It's saying the setup_toolchain script does not exist. But it does.
Also, this is not a duplicate of #16.

**Comment by chibicitiberiu** [comment]
Does the sh file have execution permissions?

chmod +x file

**Comment by ajh123** [comment]
They already did before, but doing it again still returns the same error.

**Comment by ajh123** [comment]
I tried to do the same on a Rapiberry Pi but still get the same error. However, #19 seems to fix it but a new error is introduced
```python
$ scons toolchain
scons: Reading SConscript files ...
NameError: name 'os' is not defined:
  File "/mnt/data_all/projects/gtmos/SConstruct", line 50:
    HOST_ENVIRONMENT = Environment(variables=VARS,
  File "/usr/lib/python3/dist-packages/SCons/Environment.py", line 982:
    variables.Update(self)
  File "/usr/lib/python3/dist-packages/SCons/Variables/__init__.py", line 187:
    exec(contents, {}, values)
  File "<string>", line 8:
```

And I tried to `import os` at the top of the `SConscript` but the same error was produced but with a different line number (50 -> 51)

**Comment by franticboDev** [comment]
In the config file, .toolchains is set in the parent directory. Modify it to ".toolchains" to fix it, make a the dir ".toolchains" and then run scons toolchain to build the toolchain.

**Comment by ajh123** [comment]
Right, I've remade the OS using old school Makefiles! There're probably not the best, but they work!

**Comment by ajh123** [comment]
For anyone wondering #19 does fix this issue. You may need a proper Ubuntu (like WSL2) inside of the Raspberry Pi version of Linux.
