### ISSUE TITLE
Error when booting OS from tag Part10

### ISSUE THREAD

**Issue by ItsNovaAndCrap** [nanobyte-dev/nanobyte_os#30]
First of all, I'm using Part10 instead of Part11 because I'm not that fond of using SCons as a build system and I want to stick with Make.

I've double-checked all of my code, and it's the same as the source code on the repo.
But whenever I boot with QEMU, It prints out this:
```
Hello World From Kernel!
Unhandled Exception: Segment Not Present
  EAX=0  EBX=2500  ECX=0  EDX=100b2d  ESI=7e19  EDI=245c
  ESP=10005e  EBP=ffa4  EIP=1000ba  EFLAGS=202  CS=8  DS=10  SS=100000
  Interrupt=b  Error=402
KERNEL PANIC!
```
Please let me know if I'm doing anything wrong or if I should provide something.

**Comment by chibicitiberiu** [comment]
Can you show the code at EIP=1000ba? You can figure that out by looking into the map file generated when you build the kernel (I'm assuming you have the map enabled). From there, you can find the function, and then you can do an objdump on the object file where that function is contained (that information should also be in the map file), like this: `objdump -d -M intel -S yourobjectfile.o`. With this, you can find the place in the code where the error is occurring.

Something I'm noticing here is `SS=100000`. The stack segment should be the same as DS, I think this might be your problem.

**Comment by chibicitiberiu** [comment]
`ESP=10005e ` is also suspicious. Your stack could be overwriting your code. I'm thinking that maybe you didn't set up the stack properly.

**Comment by ItsNovaAndCrap** [comment]
In my map file, crash_me() is at 1000ba. So I must be running that piece of code somewhere...
Guess it's not a bug, but a mistake on my part. Sorry about that.
I'll let you know if it works without the crash_me().

**Comment by ItsNovaAndCrap** [comment]
Yeah, it works without the crash_me()...
Can't believe I waited a week for an answer, only find out it's not a bug...
Once again, sorry for wasting your time.

**Comment by chibicitiberiu** [comment]
No worries
