### ISSUE TITLE
Request for graphics tutorial of making os

### ISSUE THREAD

**Issue by afifafifafifafifali** [nanobyte-dev/nanobyte_os#32]
Request for graphics tutorial of making os

**Comment by chibicitiberiu** [comment]
I'm planning on it, but I want to get some of the basics done first, like memory management, 64-bit, and maybe some storage drivers.

**Comment by chibicitiberiu** [comment]
In the meantime, you can check the this repo where I experiment with it a bit: https://github.com/nanobyte-dev/nanobyte_experiments/tree/master/SettingVideoModes
