### ISSUE TITLE
boot halts

### ISSUE THREAD

**Issue by GerardWassink** [nanobyte-dev/nanobyte_os#34]
I duplicated the boot.asm code and it halts in the middle of the puts routine.
Using the qemu command from the video in a terminal with the addition of the -nographic switch.
Added a couple of earlier puts calls to see if that works, see output, they do.
It's the call to puts msg_hello that grinds to a halt...

Any help please?

Below first a part of the code, that the output of my test.

===================== CODE

main:

        ; setup data segments
        mov  ax,0       ; can't write to ds/es directly
        mov  ds, ax
        mov  es, ax

        ; setup stack segment
        mov  ss, ax
        mov  sp, 0xC700 ; stack grows downwards from where we are loaded in memory

        ; print message
        mov  si, msg_read_starts
        call puts

        ; read something from floppy disk
        ; BIOS should set DL to drive number
        mov  [ebr_drive_number], dl

        mov  ax, 1      ; LBA = 1, second sector from disk
        mov  cl, 1      ; 1 sector to read
        mov  bx, 0x7E00 ; data should be after the bootloader
        call disk_read

        ; print message
        mov  si, msg_read_okay
        call puts

        ; print message
        mov  si, msg_hello
        call puts

        cli             ; disable interrupts, this way CPU can't get out of 'halt' state
        hlt

===================== TEST OUTPUT

SeaBIOS (version 1.16.2-debian-1.16.2-1)

iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+06FCF160+06F0F160 CA00

Booting from Hard Disk...
Boot failed: could not read the boot disk

Booting from Floppy...
Read from disk started
Read from disk finished okay
gawOS 0.1 startin

**Comment by chibicitiberiu** [comment]
Can you show the full source code?

**Comment by GerardWassink** [comment]
Lost my first source that I typed in myself, so can not reproduce it anymore.
Downloaded the subsequenst versions 1, 2 and 3.
Issue can be closed AFAIC.
