### ISSUE TITLE
request for adding input method

### ISSUE THREAD

**Issue by afifafifafifafifali** [nanobyte-dev/nanobyte_os#35]
dear nanobyte,
You have to implement the keyboard, mouse , and scrolling support . You have to implement these on Ep10 files .

**Comment by afifafifafifafifali** [comment]
To implement keyboard , you have to include the input reading string , and for that you must use these two lines of codes: "if(inportb(0x64) & 0x1)                 
        {
            switch(inportb(0x60))
            { //rest of the code"


and for reading input , you have to add the decimal numbers of the keyboard keys.Here's the list of the decimal numbers of the keyboard keys . 



![scancode_page1](https://github.com/nanobyte-dev/nanobyte_os/assets/98092569/9cb4567d-4241-49c2-99a7-6873d523b669)
![scancode_page2](https://github.com/nanobyte-dev/nanobyte_os/a
![scancode_page2](https://github.com/nanobyte-dev/nanobyte_os/assets/98092569/08edba22-6b43-4a94-b916-ce84927485de)
ssets/98092569/8a1e3b1a-ed4e-436c-9e53-e8251d54dc57)

**Comment by afifafifafifafifali** [comment]
Note: use the scan code line's decimal numbers.

**Comment by afifafifafifafifali** [comment]
I'm your subscriber . Here's the proof :
![Screenshot (80)](https://github.com/nanobyte-dev/nanobyte_os/assets/98092569/57fe2eaa-fda2-40ce-9814-8d512bc19749)

**Comment by afifafifafifafifali** [comment]
i did it . here's the code:
[somelogs.zip](https://github.com/nanobyte-dev/nanobyte_os/files/12393470/somelogs.zip)

**Comment by chibicitiberiu** [comment]
[This PR](https://github.com/nanobyte-dev/nanobyte_os/pull/20) implements it. I am planning on covering it at some point, but right now the priority is the following:

1. c++ migration
2. finishing memory management
3. getting to 64-bit

I'm still thinking about what I should focus on after 3, I'm currently thinking about doing graphics and then input (keys, mouse).

**Comment by afifafifafifafifali** [comment]
can you support me with the code that I have provided earlier <somelogs.zip> . it works but haves some issues

**Comment by afifafifafifafifali** [comment]
Here I have created a new file called kbio.h in kernel directory . And in main.c , i've used the readstr() method , which works fine but not in the console

**Comment by chibicitiberiu** [comment]
I see that you are using polling to read from the keyboard. This is fine for now, but it's not the right way for a multitasking operating system where you would want to use interrupts. Also, you don't have any keyboard initialization code, you're relying on whatever the BIOS set up.

Can you explain what problems are you having?

**Comment by afifafifafifafifali** [comment]
Thank you for asking me . Here's the problems screen record video: https://1drv.ms/u/s!AqjGnQyfs3mPgQ6vThOFZHKzqHV8?e=GscgGZ

**Comment by chibicitiberiu** [comment]
The problem seems to be that you're not using the same cursor position for echo-ing the typed characters and printing to the screen. Your echo'ing stuff is implemented in stdio.c, but printing stuff to the screen is in arch/i686/vga_text.c

Why are you not simply using `putc` (which uses that `stdout` special file and eventually gets to vga_text.c)?

**Comment by afifafifafifafifali** [comment]
`putc()` works but the backspace doesn't works for putc

**Comment by afifafifafifafifali** [comment]
When i type a bad command at first , it says`Bad command`, but when i type a correct command it says bad command

**Comment by afifafifafifafifali** [comment]
I have found a os developer who has implemented the input methods like mouse keyboard [https://www.youtube.com/@poncho2364](url)
