### ISSUE TITLE
/usr/bin/ld: i386 architecture of input file `build/i686_debug/stage1_fat32/boot.o' is incompatible with i386:x86-64 output

### ISSUE THREAD

**Issue by afifafifafifafifali** [nanobyte-dev/nanobyte_os#38]
`scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Linking    [build/i686_debug/stage1_fat32/stage1.bin]
/usr/bin/ld: i386 architecture of input file `build/i686_debug/stage1_fat32/boot.o' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status
scons: *** [build/i686_debug/stage1_fat32/stage1.bin] Error 1
scons: building terminated because of errors.

**Comment by chibicitiberiu** [comment]
Something is wrong. Are you using a cross compiler? Is it a 32-bit or 64-bit cross compiler?

**Comment by afifafifafifafifali** [comment]
It's 32-bit = i386

**Comment by afifafifafifafifali** [comment]
I'm using i386 instead of  i686(beacause it it the  same as i386

**Comment by twobob** [comment]
CFLAGS?=-ggdb -m32 # added -m32 for 32-bit compilation

maybe?

**Comment by afifafifafifafifali** [comment]
It's scons not make

**Comment by chibicitiberiu** [comment]
i386 means you're targeting the [386 CPU](https://en.wikipedia.org/wiki/I386). i686 means you're targeting a [Pentium Pro](https://en.wikipedia.org/wiki/Pentium_Pro). Not really the same thing. You should only use i386 if you plan to support old processors (like the original Pentium, 486 or 386).

If you want to do things this way, you have to modify the build scripts where they reference i686. In build_scripts/config.py you should set the arch properly. [Here is another place ](if HOST_ENVIRONMENT['arch'] == 'i686':) you need to modify. I recommend you search for "i686" and figure out if you need to modify anything else.

**Comment by twobob** [comment]
> It's scons not make

oh fair enough, dunno if you even need it but it would have been:

        import os

        # Parameters
        BUILD_DIR = 'build'
        CC = 'gcc'
        CFLAGS = '-ggdb -m32'

        # Create the build directory structure
        if not os.path.exists(os.path.join(BUILD_DIR, 'tools', 'fat')):
            os.makedirs(os.path.join(BUILD_DIR, 'tools', 'fat'))

        # Get the list of source files
        sources = Glob('*.c')

        # Create objects and specify their build directory
        objects = [os.path.join(BUILD_DIR, 'tools', 'fat', os.path.basename(str(src)[:-2] + '.o')) for src in sources]

        # Compile the object files
        for idx, src in enumerate(sources):
            Object(target=objects[idx], source=src, CC=CC, CCFLAGS=CFLAGS)

        # Link to create the final output
        Program(target=os.path.join(BUILD_DIR, 'tools', 'fat.out'), source=objects, CC=CC, CCFLAGS=CFLAGS)

        # Clean target
        Clean('.', os.path.join(BUILD_DIR, 'tools', 'fat.out'))
        Clean('.', os.path.join(BUILD_DIR, 'tools', 'fat'))
