### ISSUE TITLE
Part 1 main.asm forgot colon on line 57

### ISSUE THREAD

**Issue by Priff13** [nanobyte-dev/nanobyte_os#44]
https://github.com/nanobyte-dev/nanobyte_os/blob/ba9def45e5a59ecdec0570a3417920cacc532b9a/src/main.asm#L57

Change to `.halt:`

**Comment by chibicitiberiu** [comment]
You are correct. Unfortunately, I cannot modify an existing commit. I will think about a solution... maybe create a branch instead of a tag for each part.

**Comment by chibicitiberiu** [comment]
I created a [separate branch ](https://github.com/nanobyte-dev/nanobyte_os/tree/videos/Part1) for Part1 so I can add fixes. I will do this for the other parts as well and update the yt links..
