### ISSUE TITLE
Broken Makefile part one

### ISSUE THREAD

**Issue by BoxyPlayz** [nanobyte-dev/nanobyte_os#47]
im running 32 bit linux. heres error
make: *** No rule to make target 'nasm', needed by 'ASM'.  Stop.

heres code
![error](https://github.com/nanobyte-dev/nanobyte_os/assets/137698834/37a129f5-8f08-41f6-94ce-7bc61cfd4866)

**Comment by TheClogger666** [comment]
> im running 32 bit linux. heres error make: *** No rule to make target 'nasm', needed by 'ASM'. Stop.
> 
> heres code ![error](https://private-user-images.githubusercontent.com/137698834/288256084-37a129f5-8f08-41f6-94ce-7bc61cfd4866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNjI2MzAsIm5iZiI6MTcwMjA2MjMzMCwicGF0aCI6Ii8xMzc2OTg4MzQvMjg4MjU2MDg0LTM3YTEyOWY1LThmMDgtNDFmNi05NGNlLTdiYzYxY2ZkNDg2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQxOTA1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDMwOTFiZWIwN2Y1YTA0MzQ1ZDc1Yjk3NTcyZTk4NmY1MmY1ZTllNWZhNDE3ZGFjMTYwOWVkYmNiMThmYjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QPIQsNiSRCGJKep1EtsXgWhMn3WogHVltHNUIh4CmbY)

Assuming your on a Debian-based distro (e.g. Ubuntu)

sudo apt install nasm



Then re-run the build

**Comment by BoxyPlayz** [comment]
> > im running 32 bit linux. heres error make: *** No rule to make target 'nasm', needed by 'ASM'. Stop.
> > heres code ![error](https://private-user-images.githubusercontent.com/137698834/288256084-37a129f5-8f08-41f6-94ce-7bc61cfd4866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNjI2MzAsIm5iZiI6MTcwMjA2MjMzMCwicGF0aCI6Ii8xMzc2OTg4MzQvMjg4MjU2MDg0LTM3YTEyOWY1LThmMDgtNDFmNi05NGNlLTdiYzYxY2ZkNDg2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQxOTA1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDMwOTFiZWIwN2Y1YTA0MzQ1ZDc1Yjk3NTcyZTk4NmY1MmY1ZTllNWZhNDE3ZGFjMTYwOWVkYmNiMThmYjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QPIQsNiSRCGJKep1EtsXgWhMn3WogHVltHNUIh4CmbY)
> 
> Assuming your on a Debian-based distro (e.g. Ubuntu)
> 
> sudo apt install nasm
> 
> Then re-run the build

says "nasm is already the newest version (2.13.02-0.1)."

**Comment by BoxyPlayz** [comment]
Figured out how to fix it

**Comment by chibicitiberiu** [comment]
Could you share how you fixed it, so others that encounter this problem will be able to find the solution? Thank you.
