### ISSUE TITLE
/bin/sh: 1: mcopy: not found

### ISSUE THREAD

**Issue by MazdakShafieiSabet** [nanobyte-dev/nanobyte_os#61]
Hello! I am using Ubuntu 24.02 under WSL2 on a Windows machine. When I run "make" I get this error message:
user@computer:~/OsDev/nanobyte_os$ make
mkdir -p build
nasm src/bootloader/boot.asm -f bin -o build/bootloader.bin
nasm src/kernel/main.asm -f bin -o build/kernel.bin
dd if=/dev/zero of=build/main_floppy.img bs=512 count=2880
2880+0 records in
2880+0 records out
1474560 bytes (1.5 MB, 1.4 MiB) copied, 0.00268983 s, 548 MB/s
mkfs.fat -F 12 -n "NBOS" build/main_floppy.img
mkfs.fat 4.2 (2021-01-31)
dd if=build/bootloader.bin of=build/main_floppy.img conv=notrunc
1+0 records in
1+0 records out
512 bytes copied, 5.6621e-05 s, 9.0 MB/s
mcopy -i build/main_floppy.img build/kernel.bin "::kernel.bin"
/bin/sh: 1: mcopy: not found
make: *** [Makefile:17: build/main_floppy.img] Error 127

This speific instance of the error is after I have copied the contents of the files here on GitHub, as the tutorial video didn't have this error and I don't quite know what to do now. Any help is greatly appreciated.

**Comment by ViktorPopp** [comment]
You will need to install mtools.

**Comment by MazdakShafieiSabet** [comment]
Thank you, I'll make sure to do that next time.
