### ISSUE TITLE
Makefile:7: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by Mastergamer433** [nanobyte-dev/nanobyte_os#8]
Hi im near 8:50 in your first video in the tutorial series and i am getting this error when i try running make:
Makefile:7: *** missing separator.  Stop.

Here is my Makefile:

```Makefile
ASM=nasm

SRC_DIR=src
BUILD_DIR=build

$(BUILD_DIR)/main_floppy.img: $(BUILD_DIR)/main.bin
    cp $(BUILD_DIR)/main.bin $(BUILD_DIR)/main_floppy.img
    truncate -s 1440k $(BUILD_DIR)/main_floppy.img

$(BUILD_DIR)/main.bin: $(SRC_DIR)/main.asm
    $(ASM) $(SRC_DIR)/main.asm -f bin -o $(BUILD_DIR)/main.bin
```

Here is the output of the nice command tree:
`
.
|-- Makefile
|-- build
`-- src
    `-- main.asm
`

my os is Arch linux.
heres a neofetch of the system:

`
mg433@Birk 
---------- 
OS: Arch Linux x86_64 
Kernel: 5.18.16-arch1-1 
Uptime: 33 mins 
Packages: 1218 (pacman) 
Shell: zsh 5.9 
Resolution: 2560x1440 
WM: herbstluftwm 
Theme: Adwaita [GTK2], Dracula-alt-style [GTK3] 
Icons: Adwaita [GTK2], dracula-icons-main [GTK3] 
CPU: Intel i5-9400F (6) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 1660 Ti 
Memory: 1879MiB / 15915MiB 
`

the version of make is 4.3

**Comment by Andrej123456789** [comment]
Check if you are using tabs or spaces (try invert them)

**Comment by Mastergamer433** [comment]
it worked to use tabs instead of spaces.
